// GENERATED by tool/gen_gallery.dart from gallery.spec.json and
// contracts/components.manifest.json — DO NOT EDIT.
// Regenerate: dart run tool/gen_gallery.dart

import 'package:flutter/widgets.dart';

import 'coverage.dart';

const ComponentCoverage _kunAutocomplete = ComponentCoverage(
  name: 'KunAutocomplete',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'allowCustomValue',
      status: CoverageStatus.shown,
      dartName: 'allowCustomValue',
      shownBy: 'Free text',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.noVisualForm,
      dartName: 'semanticLabel',
      reason:
          'An accessible name has no visual form; every demo here has a visible label, and what is announced is asserted by the widget tests.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'clearable',
      status: CoverageStatus.shown,
      dartName: 'clearable',
      shownBy: 'Free text',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Sizes and states',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'darkBorder',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'No-op since 0.18.0. Every neutral border now resolves to the unified `--color-kun-border` token (the `border-kun` utility), which already flips light↔dark — so the old light-translucent / dark-solid split this prop toggled is gone. Safe to remove from call sites.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'debounce',
      status: CoverageStatus.shown,
      dartName: 'debounce',
      shownBy: 'A remote source',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Sizes and states',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'Sizes and states',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Sizes and states',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isInvalid',
      status: CoverageStatus.noVisualForm,
      dartName: 'isInvalid',
      reason:
          'The invalid styling with no message is what `error` already renders, minus the line — there is nothing a demo could show that the error demo does not.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'loading',
      status: CoverageStatus.shown,
      dartName: 'loading',
      shownBy: 'A remote source',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'loadingText',
      status: CoverageStatus.notYet,
      dartName: 'loadingText',
      reason:
          'The remote demo leaves it at the locale default; a demo that only swaps the string shows the string, not the component.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'manualFilter',
      status: CoverageStatus.shown,
      dartName: 'manualFilter',
      shownBy: 'A remote source',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'noResultText',
      status: CoverageStatus.notYet,
      dartName: 'noResultText',
      reason:
          'The same: the basic demo shows the locale default when nothing matches.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'options',
      status: CoverageStatus.shown,
      dartName: 'options',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placeholder',
      status: CoverageStatus.shown,
      dartName: 'placeholder',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.notYet,
      dartName: 'rounded',
      reason:
          'The rounding steps belong on one demo across every field, which KunInput\'s does not have either.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes and states',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'search',
      status: CoverageStatus.shown,
      dartName: 'onSearch',
      shownBy: 'A remote source',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'select',
      status: CoverageStatus.shown,
      dartName: 'onSelected',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'option',
      status: CoverageStatus.shown,
      dartName: 'optionBuilder',
      shownBy: 'Custom rows',
    ),
  ],
);

/// The contract coverage page for KunAutocomplete.
Widget kunAutocompleteContract(BuildContext context) =>
    const CoveragePage(coverage: _kunAutocomplete);

const ComponentCoverage _kunAvatar = ComponentCoverage(
  name: 'KunAvatar',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'decoration',
      status: CoverageStatus.shown,
      dartName: 'decoration',
      shownBy: 'Decoration',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disableFloating',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Deprecated no-op on the web: KunAvatar renders no floating card. The port starts without it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'floatingPosition',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Deprecated no-op on the web: KunAvatar renders no floating card. The port starts without it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isNavigation',
      status: CoverageStatus.shown,
      dartName: 'isNavigation',
      shownBy: 'Navigation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'user',
      status: CoverageStatus.shown,
      dartName: 'user',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunAvatar.
Widget kunAvatarContract(BuildContext context) =>
    const CoveragePage(coverage: _kunAvatar);

const ComponentCoverage _kunBadge = ComponentCoverage(
  name: 'KunBadge',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.shown,
      dartName: 'semanticLabel',
      shownBy: 'Standalone',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Colors',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'count',
      status: CoverageStatus.shown,
      dartName: 'count',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'max',
      status: CoverageStatus.shown,
      dartName: 'max',
      shownBy: 'Max',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placement',
      status: CoverageStatus.shown,
      dartName: 'placement',
      shownBy: 'Placement',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'show',
      status: CoverageStatus.shown,
      dartName: 'show',
      shownBy: 'Count',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'showZero',
      status: CoverageStatus.shown,
      dartName: 'showZero',
      shownBy: 'Count',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Dot',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunBadge.
Widget kunBadgeContract(BuildContext context) =>
    const CoveragePage(coverage: _kunBadge);

const ComponentCoverage _kunButton = ComponentCoverage(
  name: 'KunButton',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.noVisualForm,
      dartName: 'semanticLabel',
      reason:
          'An accessible name has no visual form. The sizes demo sets one on every icon-only button because the contract requires it there, but what is announced is asserted by the widget tests, not seen in a gallery.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'fullWidth',
      status: CoverageStatus.shown,
      dartName: 'fullWidth',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'icon',
      status: CoverageStatus.shown,
      dartName: 'icon',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'iconPosition',
      status: CoverageStatus.notYet,
      dartName: 'iconPosition',
      reason:
          'The sizes demo places its icon in the default left position only.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isIconOnly',
      status: CoverageStatus.shown,
      dartName: 'isIconOnly',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'loading',
      status: CoverageStatus.shown,
      dartName: 'loading',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounded',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'click',
      status: CoverageStatus.noVisualForm,
      dartName: 'onPressed',
      reason:
          'Every button in every demo carries a live onPressed -- that is the floor this gallery was built to meet. A callback has no appearance of its own to show.',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'icon',
      status: CoverageStatus.shown,
      dartName: 'icon',
      shownBy: 'Sizes',
    ),
  ],
);

/// The contract coverage page for KunButton.
Widget kunButtonContract(BuildContext context) =>
    const CoveragePage(coverage: _kunButton);

const ComponentCoverage _kunCard = ComponentCoverage(
  name: 'KunCard',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'bordered',
      status: CoverageStatus.shown,
      dartName: 'bordered',
      shownBy: 'Surfaces',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'clickable',
      status: CoverageStatus.shown,
      dartName: 'clickable',
      shownBy: 'Interactive',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Tints',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'darkBorder',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Declared in Card.vue\'s props but never read by its template — a legacy toggle with no behaviour to port.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isHoverable',
      status: CoverageStatus.shown,
      dartName: 'isHoverable',
      shownBy: 'Interactive',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isTransparent',
      status: CoverageStatus.shown,
      dartName: 'isTransparent',
      shownBy: 'Surfaces',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'padding',
      status: CoverageStatus.shown,
      dartName: 'padding',
      shownBy: 'Padding',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounded',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'click',
      status: CoverageStatus.noVisualForm,
      dartName: 'onTap',
      reason:
          'Every card in the Interactive demo carries a live onTap, and the prop\'s one subtlety -- that it fires whether or not the card is clickable -- is a behaviour, not an appearance. A callback has nothing of its own to show.',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'cover',
      status: CoverageStatus.shown,
      dartName: 'cover',
      shownBy: 'Anatomy',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Anatomy',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'footer',
      status: CoverageStatus.shown,
      dartName: 'footer',
      shownBy: 'Anatomy',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'header',
      status: CoverageStatus.shown,
      dartName: 'header',
      shownBy: 'Anatomy',
    ),
  ],
);

/// The contract coverage page for KunCard.
Widget kunCardContract(BuildContext context) =>
    const CoveragePage(coverage: _kunCard);

const ComponentCoverage _kunCheckBox = ComponentCoverage(
  name: 'KunCheckBox',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Colours',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Help text',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Help text',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'id',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The DOM id exists to wire `<label for>` and `aria-describedby` to the input. The label is inside the widget here and the description sits on its semantics node, so there is nothing for an id to address.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'indeterminate',
      status: CoverageStatus.shown,
      dartName: 'indeterminate',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'type',
      status: CoverageStatus.shown,
      dartName: 'type',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'value',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The native `<input value>`, which only a form submission or a native checkbox group reads. Flutter has neither; KunCheckBoxGroup carries each option\'s value on the option.',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'change',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Fires on exactly the toggles update:modelValue fires on, with the same boolean; onChanged answers both.',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'With a widget',
    ),
  ],
);

/// The contract coverage page for KunCheckBox.
Widget kunCheckBoxContract(BuildContext context) =>
    const CoveragePage(coverage: _kunCheckBox);

const ComponentCoverage _kunCheckBoxGroup = ComponentCoverage(
  name: 'KunCheckBoxGroup',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.noVisualForm,
      dartName: 'semanticLabel',
      reason:
          'An accessible name has no visual form. The states demo names a group with it where there is no visible label, and what is announced is asserted by the widget tests.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Sizes and colours',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'hideIndicator',
      status: CoverageStatus.shown,
      dartName: 'hideIndicator',
      shownBy: 'Orientation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'max',
      status: CoverageStatus.shown,
      dartName: 'max',
      shownBy: 'A capped selection',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'values',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'options',
      status: CoverageStatus.shown,
      dartName: 'options',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'orientation',
      status: CoverageStatus.shown,
      dartName: 'orientation',
      shownBy: 'Orientation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Orientation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes and colours',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Variants',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'change',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Fires on exactly the toggles update:modelValue fires on, with the same list; onChanged answers both and carries the new list rather than a read-back.',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'invalid',
      status: CoverageStatus.shown,
      dartName: 'onInvalid',
      shownBy: 'A capped selection',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunCheckBoxGroup.
Widget kunCheckBoxGroupContract(BuildContext context) =>
    const CoveragePage(coverage: _kunCheckBoxGroup);

const ComponentCoverage _kunChip = ComponentCoverage(
  name: 'KunChip',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'closable',
      status: CoverageStatus.shown,
      dartName: 'closable',
      shownBy: 'Parts',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'Parts',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'close',
      status: CoverageStatus.shown,
      dartName: 'onClose',
      shownBy: 'Dismiss',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'end',
      status: CoverageStatus.shown,
      dartName: 'end',
      shownBy: 'Parts',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'start',
      status: CoverageStatus.shown,
      dartName: 'start',
      shownBy: 'Parts',
    ),
  ],
);

/// The contract coverage page for KunChip.
Widget kunChipContract(BuildContext context) =>
    const CoveragePage(coverage: _kunChip);

const ComponentCoverage _kunDivider = ComponentCoverage(
  name: 'KunDivider',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'borderStyle',
      status: CoverageStatus.shown,
      dartName: 'borderStyle',
      shownBy: 'Colours and dashes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Colours and dashes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'orientation',
      status: CoverageStatus.shown,
      dartName: 'orientation',
      shownBy: 'Orientation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'withLabel',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Deprecated no-op on the web: the label renders whenever the slot has content, which in Dart is whenever `child` is not null.',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunDivider.
Widget kunDividerContract(BuildContext context) =>
    const CoveragePage(coverage: _kunDivider);

const ComponentCoverage _kunDropdown = ComponentCoverage(
  name: 'KunDropdown',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'Disabled',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'items',
      status: CoverageStatus.shown,
      dartName: 'items',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'minWidth',
      status: CoverageStatus.shown,
      dartName: 'minWidth',
      shownBy: 'Minimum width',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'position',
      status: CoverageStatus.shown,
      dartName: 'position',
      shownBy: 'Positions',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'close',
      status: CoverageStatus.shown,
      dartName: 'onClose',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'open',
      status: CoverageStatus.shown,
      dartName: 'onOpen',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'select',
      status: CoverageStatus.shown,
      dartName: 'onSelected',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'trigger',
      status: CoverageStatus.shown,
      dartName: 'trigger',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunDropdown.
Widget kunDropdownContract(BuildContext context) =>
    const CoveragePage(coverage: _kunDropdown);

const ComponentCoverage _kunInput = ComponentCoverage(
  name: 'KunInput',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'autofocus',
      status: CoverageStatus.notYet,
      dartName: 'autofocus',
      reason:
          'A demo page is the payload of an iframe, and a field that takes focus on mount steals the caret from the page hosting it. Showing this honestly needs a mount-on-demand control the gallery does not have.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Focus ring',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'darkBorder',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Declared in Input.vue\'s props but never read by its template — a legacy toggle with no behaviour to port.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Validation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'helperText',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The web\'s own deprecated alias of `description`; a new API is not born with it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isClearable',
      status: CoverageStatus.shown,
      dartName: 'isClearable',
      shownBy: 'Affixes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isInvalid',
      status: CoverageStatus.shown,
      dartName: 'isInvalid',
      shownBy: 'Validation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placeholder',
      status: CoverageStatus.shown,
      dartName: 'placeholder',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'required',
      status: CoverageStatus.shown,
      dartName: 'required',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'revealPassword',
      status: CoverageStatus.shown,
      dartName: 'revealPassword',
      shownBy: 'Affixes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounded',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'type',
      status: CoverageStatus.shown,
      dartName: 'type',
      shownBy: 'Affixes',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'blur',
      status: CoverageStatus.shown,
      dartName: 'onBlur',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'clear',
      status: CoverageStatus.shown,
      dartName: 'onClear',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'focus',
      status: CoverageStatus.shown,
      dartName: 'onFocus',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'prefix',
      status: CoverageStatus.shown,
      dartName: 'prefix',
      shownBy: 'Affixes',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'suffix',
      status: CoverageStatus.shown,
      dartName: 'suffix',
      shownBy: 'Affixes',
    ),
  ],
);

/// The contract coverage page for KunInput.
Widget kunInputContract(BuildContext context) =>
    const CoveragePage(coverage: _kunInput);

const ComponentCoverage _kunLoading = ComponentCoverage(
  name: 'KunLoading',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Its line',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'loading',
      status: CoverageStatus.shown,
      dartName: 'loading',
      shownBy: 'Over content',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Compact',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'spinner',
      status: CoverageStatus.shown,
      dartName: 'spinner',
      shownBy: 'Compact',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'src',
      status: CoverageStatus.shown,
      dartName: 'image',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Over content',
    ),
  ],
);

/// The contract coverage page for KunLoading.
Widget kunLoadingContract(BuildContext context) =>
    const CoveragePage(coverage: _kunLoading);

const ComponentCoverage _kunModal = ComponentCoverage(
  name: 'KunModal',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.shown,
      dartName: 'semanticLabel',
      shownBy: 'Alert dialog',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isCloseRequestDismissable',
      status: CoverageStatus.shown,
      dartName: 'isCloseRequestDismissable',
      shownBy: 'Non-dismissable',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isDismissable',
      status: CoverageStatus.shown,
      dartName: 'isDismissable',
      shownBy: 'Non-dismissable',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isShowCloseButton',
      status: CoverageStatus.shown,
      dartName: 'isShowCloseButton',
      shownBy: 'Non-dismissable',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isSwipeDismissable',
      status: CoverageStatus.shown,
      dartName: 'isSwipeDismissable',
      shownBy: 'Placement',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placement',
      status: CoverageStatus.shown,
      dartName: 'placement',
      shownBy: 'Placement',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'role',
      status: CoverageStatus.shown,
      dartName: 'role',
      shownBy: 'Alert dialog',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Form',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'scrollBehavior',
      status: CoverageStatus.shown,
      dartName: 'scrollBehavior',
      shownBy: 'Scroll behaviour',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'title',
      status: CoverageStatus.shown,
      dartName: 'title',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'withContainer',
      status: CoverageStatus.shown,
      dartName: 'withContainer',
      shownBy: 'Without container',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'close',
      status: CoverageStatus.shown,
      dartName: 'onClose',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunModal.
Widget kunModalContract(BuildContext context) =>
    const CoveragePage(coverage: _kunModal);

const ComponentCoverage _kunNavItem = ComponentCoverage(
  name: 'KunNavItem',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Rail',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'current',
      status: CoverageStatus.shown,
      dartName: 'current',
      shownBy: 'Rail',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'Sidebar',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'href',
      status: CoverageStatus.noVisualForm,
      dartName: 'href',
      reason:
          'A href is a navigation token handed to KunUIConfig.navigate; it has no visual of its own. The widget tests fire navigate with it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'icon',
      status: CoverageStatus.shown,
      dartName: 'icon',
      shownBy: 'Rail',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Rail',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'stacked',
      status: CoverageStatus.shown,
      dartName: 'stacked',
      shownBy: 'Rail',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'click',
      status: CoverageStatus.shown,
      dartName: 'onPressed',
      shownBy: 'Rail',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'icon',
      status: CoverageStatus.shown,
      dartName: 'icon',
      shownBy: 'Badge',
    ),
  ],
);

/// The contract coverage page for KunNavItem.
Widget kunNavItemContract(BuildContext context) =>
    const CoveragePage(coverage: _kunNavItem);

const ComponentCoverage _kunNull = ComponentCoverage(
  name: 'KunNull',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Default',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isShowSticker',
      status: CoverageStatus.shown,
      dartName: 'isShowSticker',
      shownBy: 'Custom',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'src',
      status: CoverageStatus.shown,
      dartName: 'image',
      shownBy: 'Custom',
    ),
  ],
);

/// The contract coverage page for KunNull.
Widget kunNullContract(BuildContext context) =>
    const CoveragePage(coverage: _kunNull);

const ComponentCoverage _kunPopover = ComponentCoverage(
  name: 'KunPopover',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.noVisualForm,
      dartName: 'semanticLabel',
      reason:
          'An accessible name has no visual form. Every demo leaves it at the web\'s own fallback and what is announced is asserted by the widget tests.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'autoPosition',
      status: CoverageStatus.shown,
      dartName: 'autoPosition',
      shownBy: 'Collision handling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'closeDelay',
      status: CoverageStatus.shown,
      dartName: 'closeDelay',
      shownBy: 'Hover menus',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'fullWidth',
      status: CoverageStatus.shown,
      dartName: 'fullWidth',
      shownBy: 'Full width',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'group',
      status: CoverageStatus.shown,
      dartName: 'group',
      shownBy: 'Hover menus',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'opaque',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The web\'s `--kun-surface-opacity` is a CSS variable a site lowers to frost every surface; this port has no such global knob and paints `content1` opaque, so there is no translucency for the prop to override.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'openDelay',
      status: CoverageStatus.shown,
      dartName: 'openDelay',
      shownBy: 'Hover menus',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'position',
      status: CoverageStatus.shown,
      dartName: 'position',
      shownBy: 'Positions',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Arrow',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'showArrow',
      status: CoverageStatus.shown,
      dartName: 'showArrow',
      shownBy: 'Arrow',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'trigger',
      status: CoverageStatus.shown,
      dartName: 'openOn',
      shownBy: 'Hover menus',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'trigger',
      status: CoverageStatus.shown,
      dartName: 'trigger',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunPopover.
Widget kunPopoverContract(BuildContext context) =>
    const CoveragePage(coverage: _kunPopover);

const ComponentCoverage _kunProgress = ComponentCoverage(
  name: 'KunProgress',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.noVisualForm,
      dartName: 'semanticLabel',
      reason:
          'An accessible name has no visual form; what a progressbar announces is asserted by the widget tests.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Colours',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'indeterminate',
      status: CoverageStatus.shown,
      dartName: 'indeterminate',
      shownBy: 'Indeterminate',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'max',
      status: CoverageStatus.shown,
      dartName: 'max',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounding',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'showLabel',
      status: CoverageStatus.shown,
      dartName: 'showLabel',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'value',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Variants',
    ),
  ],
);

/// The contract coverage page for KunProgress.
Widget kunProgressContract(BuildContext context) =>
    const CoveragePage(coverage: _kunProgress);

const ComponentCoverage _kunRadioGroup = ComponentCoverage(
  name: 'KunRadioGroup',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.noVisualForm,
      dartName: 'semanticLabel',
      reason:
          'An accessible name has no visual form. The states demo names a group with it where there is no visible label, and what is announced is asserted by the widget tests.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Sizes and colours',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'hideIndicator',
      status: CoverageStatus.shown,
      dartName: 'hideIndicator',
      shownBy: 'Cards',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'options',
      status: CoverageStatus.shown,
      dartName: 'options',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'orientation',
      status: CoverageStatus.shown,
      dartName: 'orientation',
      shownBy: 'Orientation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Cards',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes and colours',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Variants',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'change',
      status: CoverageStatus.shown,
      dartName: 'onSelected',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunRadioGroup.
Widget kunRadioGroupContract(BuildContext context) =>
    const CoveragePage(coverage: _kunRadioGroup);

const ComponentCoverage _kunSelect = ComponentCoverage(
  name: 'KunSelect',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.shown,
      dartName: 'semanticLabel',
      shownBy: 'Filter bar',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'clearable',
      status: CoverageStatus.shown,
      dartName: 'clearable',
      shownBy: 'Clearable',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Colors',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'darkBorder',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'No-op since 0.18.0. Every neutral border now resolves to the unified `--color-kun-border` token (the `border-kun` utility), which already flips light↔dark — so the old light-translucent / dark-solid split this prop toggled is gone. Safe to remove from call sites.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'debounce',
      status: CoverageStatus.shown,
      dartName: 'debounce',
      shownBy: 'Async',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'Disabled',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Error',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'fullWidth',
      status: CoverageStatus.shown,
      dartName: 'fullWidth',
      shownBy: 'Filter bar',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'icon',
      status: CoverageStatus.shown,
      dartName: 'icon',
      shownBy: 'Filter bar',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'loading',
      status: CoverageStatus.shown,
      dartName: 'loading',
      shownBy: 'Async',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'loadingText',
      status: CoverageStatus.shown,
      dartName: 'loadingText',
      shownBy: 'Async',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'manualFilter',
      status: CoverageStatus.shown,
      dartName: 'manualFilter',
      shownBy: 'Async',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'maxVisibleTags',
      status: CoverageStatus.shown,
      dartName: 'maxVisibleTags',
      shownBy: 'Filter bar',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value / values',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'multiple',
      status: CoverageStatus.shown,
      dartName: 'KunSelect.multiple',
      shownBy: 'Multiple',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'noResultText',
      status: CoverageStatus.shown,
      dartName: 'noResultText',
      shownBy: 'Async',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'options',
      status: CoverageStatus.shown,
      dartName: 'options',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placeholder',
      status: CoverageStatus.shown,
      dartName: 'placeholder',
      shownBy: 'Clearable',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'popupWidth',
      status: CoverageStatus.shown,
      dartName: 'popupWidth',
      shownBy: 'Filter bar',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'searchable',
      status: CoverageStatus.shown,
      dartName: 'searchable',
      shownBy: 'Searchable',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'searchPlaceholder',
      status: CoverageStatus.shown,
      dartName: 'searchPlaceholder',
      shownBy: 'Async',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'search',
      status: CoverageStatus.shown,
      dartName: 'onSearch',
      shownBy: 'Async',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'set',
      status: CoverageStatus.shown,
      dartName: 'onSet',
      shownBy: 'Multiple',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged / onValuesChanged',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'option',
      status: CoverageStatus.shown,
      dartName: 'optionBuilder',
      shownBy: 'Custom option',
    ),
  ],
);

/// The contract coverage page for KunSelect.
Widget kunSelectContract(BuildContext context) =>
    const CoveragePage(coverage: _kunSelect);

const ComponentCoverage _kunSkeleton = ComponentCoverage(
  name: 'KunSkeleton',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'animation',
      status: CoverageStatus.shown,
      dartName: 'animation',
      shownBy: 'Variants',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'height',
      status: CoverageStatus.shown,
      dartName: 'height',
      shownBy: 'Shapes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'loaded',
      status: CoverageStatus.shown,
      dartName: 'loaded',
      shownBy: 'Loaded',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Variants',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Variants',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'width',
      status: CoverageStatus.shown,
      dartName: 'width',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Loaded',
    ),
  ],
);

/// The contract coverage page for KunSkeleton.
Widget kunSkeletonContract(BuildContext context) =>
    const CoveragePage(coverage: _kunSkeleton);

const ComponentCoverage _kunSwitch = ComponentCoverage(
  name: 'KunSwitch',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Help text',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Help text',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Events',
    ),
  ],
);

/// The contract coverage page for KunSwitch.
Widget kunSwitchContract(BuildContext context) =>
    const CoveragePage(coverage: _kunSwitch);

const ComponentCoverage _kunTab = ComponentCoverage(
  name: 'KunTab',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'align',
      status: CoverageStatus.shown,
      dartName: 'align',
      shownBy: 'Align',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Colors',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disableAnimation',
      status: CoverageStatus.shown,
      dartName: 'disableAnimation',
      shownBy: 'Scrollable',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'Disabled',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'fullWidth',
      status: CoverageStatus.shown,
      dartName: 'fullWidth',
      shownBy: 'Full width',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'iconSize',
      status: CoverageStatus.shown,
      dartName: 'iconSize',
      shownBy: 'Custom tabs',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'items',
      status: CoverageStatus.shown,
      dartName: 'items',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'orientation',
      status: CoverageStatus.shown,
      dartName: 'orientation',
      shownBy: 'Vertical',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'scrollButtons',
      status: CoverageStatus.shown,
      dartName: 'scrollButtons',
      shownBy: 'Overflow',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'scrollable',
      status: CoverageStatus.shown,
      dartName: 'scrollable',
      shownBy: 'Scrollable',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Variants',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'change',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Fires on exactly the selections update:modelValue fires on, with the same value; onChanged answers both.',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'tab',
      status: CoverageStatus.shown,
      dartName: 'tabBuilder',
      shownBy: 'Custom tabs',
    ),
  ],
);

/// The contract coverage page for KunTab.
Widget kunTabContract(BuildContext context) =>
    const CoveragePage(coverage: _kunTab);

const ComponentCoverage _kunTextarea = ComponentCoverage(
  name: 'KunTextarea',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'autoGrow',
      status: CoverageStatus.shown,
      dartName: 'autoGrow',
      shownBy: 'Growth',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'autofocus',
      status: CoverageStatus.notYet,
      dartName: 'autofocus',
      reason:
          'A demo page is the payload of an iframe, and a field that takes focus on mount steals the caret from the page hosting it. Showing this honestly needs a mount-on-demand control the gallery does not have.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Focus ring',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'darkBorder',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Declared in Textarea.vue\'s props but never read by its template — a legacy toggle with no behaviour to port.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Validation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'hint',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The web\'s own deprecated alias of `description`; a new API is not born with it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'maxHeight',
      status: CoverageStatus.shown,
      dartName: 'maxHeight',
      shownBy: 'Growth',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'maxlength',
      status: CoverageStatus.shown,
      dartName: 'maxLength',
      shownBy: 'Count',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'minlength',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Feeds only the browser\'s submit-time constraint validation, which the component itself never renders; Flutter has no form submission for it to join.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placeholder',
      status: CoverageStatus.shown,
      dartName: 'placeholder',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'readonly',
      status: CoverageStatus.shown,
      dartName: 'readOnly',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'required',
      status: CoverageStatus.shown,
      dartName: 'required',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'resize',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The drag handle is the browser\'s own textarea chrome (CSS `resize`); Flutter text fields have none, and drawing one would be design upstream never specified. The port renders the web default, `none`.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounded',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rows',
      status: CoverageStatus.shown,
      dartName: 'rows',
      shownBy: 'Growth',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'showCharCount',
      status: CoverageStatus.shown,
      dartName: 'showCharCount',
      shownBy: 'Count',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'blur',
      status: CoverageStatus.shown,
      dartName: 'onBlur',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'focus',
      status: CoverageStatus.shown,
      dartName: 'onFocus',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'input',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Carries the DOM event of each edit; the value it reports reaches onChanged (update:modelValue) on the same edit.',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Events',
    ),
  ],
);

/// The contract coverage page for KunTextarea.
Widget kunTextareaContract(BuildContext context) =>
    const CoveragePage(coverage: _kunTextarea);

const ComponentCoverage _kunTooltip = ComponentCoverage(
  name: 'KunTooltip',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'delayHide',
      status: CoverageStatus.shown,
      dartName: 'delayHide',
      shownBy: 'Delays',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'delayShow',
      status: CoverageStatus.shown,
      dartName: 'delayShow',
      shownBy: 'Delays',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'hideOnMobile',
      status: CoverageStatus.shown,
      dartName: 'hideOnMobile',
      shownBy: 'Narrow views',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'position',
      status: CoverageStatus.shown,
      dartName: 'position',
      shownBy: 'Positions',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Arrow',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'showArrow',
      status: CoverageStatus.shown,
      dartName: 'showArrow',
      shownBy: 'Arrow',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'text',
      status: CoverageStatus.shown,
      dartName: 'text',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'content',
      status: CoverageStatus.shown,
      dartName: 'content',
      shownBy: 'Rich content',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunTooltip.
Widget kunTooltipContract(BuildContext context) =>
    const CoveragePage(coverage: _kunTooltip);

const ComponentCoverage _kunUserChip = ComponentCoverage(
  name: 'KunUserChip',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Description',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disableFloating',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Deprecated no-op on the web: KunUserChip renders no floating card. The port starts without it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'floatingPosition',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Deprecated no-op on the web: KunUserChip renders no floating card. The port starts without it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isNavigation',
      status: CoverageStatus.shown,
      dartName: 'isNavigation',
      shownBy: 'Navigation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Description',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'user',
      status: CoverageStatus.shown,
      dartName: 'user',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunUserChip.
Widget kunUserChipContract(BuildContext context) =>
    const CoveragePage(coverage: _kunUserChip);
