// GENERATED by tool/gen_gallery.dart from gallery.spec.json and
// contracts/components.manifest.json — DO NOT EDIT.
// Regenerate: dart run tool/gen_gallery.dart

import 'package:flutter/widgets.dart';

import 'coverage.dart';

const ComponentCoverage _kunBadge = ComponentCoverage(
  name: 'KunBadge',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.shown,
      dartName: 'semanticLabel',
      shownBy: 'Standalone',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Colors',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'count',
      status: CoverageStatus.shown,
      dartName: 'count',
      shownBy: 'Basic',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'max',
      status: CoverageStatus.shown,
      dartName: 'max',
      shownBy: 'Max',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placement',
      status: CoverageStatus.shown,
      dartName: 'placement',
      shownBy: 'Placement',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'show',
      status: CoverageStatus.shown,
      dartName: 'show',
      shownBy: 'Count',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'showZero',
      status: CoverageStatus.shown,
      dartName: 'showZero',
      shownBy: 'Count',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Dot',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Basic',
    ),
  ],
);

/// The contract coverage page for KunBadge.
Widget kunBadgeContract(BuildContext context) =>
    const CoveragePage(coverage: _kunBadge);

const ComponentCoverage _kunButton = ComponentCoverage(
  name: 'KunButton',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'ariaLabel',
      status: CoverageStatus.noVisualForm,
      dartName: 'semanticLabel',
      reason:
          'An accessible name has no visual form. The sizes demo sets one on every icon-only button because the contract requires it there, but what is announced is asserted by the widget tests, not seen in a gallery.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'fullWidth',
      status: CoverageStatus.shown,
      dartName: 'fullWidth',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'icon',
      status: CoverageStatus.shown,
      dartName: 'icon',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'iconPosition',
      status: CoverageStatus.notYet,
      dartName: 'iconPosition',
      reason:
          'The sizes demo places its icon in the default left position only.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isIconOnly',
      status: CoverageStatus.shown,
      dartName: 'isIconOnly',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'loading',
      status: CoverageStatus.shown,
      dartName: 'loading',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounded',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'click',
      status: CoverageStatus.noVisualForm,
      dartName: 'onPressed',
      reason:
          'Every button in every demo carries a live onPressed -- that is the floor this gallery was built to meet. A callback has no appearance of its own to show.',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'icon',
      status: CoverageStatus.shown,
      dartName: 'icon',
      shownBy: 'Sizes',
    ),
  ],
);

/// The contract coverage page for KunButton.
Widget kunButtonContract(BuildContext context) =>
    const CoveragePage(coverage: _kunButton);

const ComponentCoverage _kunCard = ComponentCoverage(
  name: 'KunCard',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'bordered',
      status: CoverageStatus.shown,
      dartName: 'bordered',
      shownBy: 'Surfaces',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'clickable',
      status: CoverageStatus.shown,
      dartName: 'clickable',
      shownBy: 'Interactive',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Tints',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'darkBorder',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Declared in Card.vue\'s props but never read by its template — a legacy toggle with no behaviour to port.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isHoverable',
      status: CoverageStatus.shown,
      dartName: 'isHoverable',
      shownBy: 'Interactive',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isTransparent',
      status: CoverageStatus.shown,
      dartName: 'isTransparent',
      shownBy: 'Surfaces',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'padding',
      status: CoverageStatus.shown,
      dartName: 'padding',
      shownBy: 'Padding',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounded',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'click',
      status: CoverageStatus.noVisualForm,
      dartName: 'onTap',
      reason:
          'Every card in the Interactive demo carries a live onTap, and the prop\'s one subtlety -- that it fires whether or not the card is clickable -- is a behaviour, not an appearance. A callback has nothing of its own to show.',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'cover',
      status: CoverageStatus.shown,
      dartName: 'cover',
      shownBy: 'Anatomy',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Anatomy',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'footer',
      status: CoverageStatus.shown,
      dartName: 'footer',
      shownBy: 'Anatomy',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'header',
      status: CoverageStatus.shown,
      dartName: 'header',
      shownBy: 'Anatomy',
    ),
  ],
);

/// The contract coverage page for KunCard.
Widget kunCardContract(BuildContext context) =>
    const CoveragePage(coverage: _kunCard);

const ComponentCoverage _kunChip = ComponentCoverage(
  name: 'KunChip',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'closable',
      status: CoverageStatus.shown,
      dartName: 'closable',
      shownBy: 'Parts',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'Parts',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'variant',
      status: CoverageStatus.shown,
      dartName: 'variant',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'close',
      status: CoverageStatus.shown,
      dartName: 'onClose',
      shownBy: 'Dismiss',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'default',
      status: CoverageStatus.shown,
      dartName: 'child',
      shownBy: 'Matrix',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'end',
      status: CoverageStatus.shown,
      dartName: 'end',
      shownBy: 'Parts',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'start',
      status: CoverageStatus.shown,
      dartName: 'start',
      shownBy: 'Parts',
    ),
  ],
);

/// The contract coverage page for KunChip.
Widget kunChipContract(BuildContext context) =>
    const CoveragePage(coverage: _kunChip);

const ComponentCoverage _kunInput = ComponentCoverage(
  name: 'KunInput',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'autofocus',
      status: CoverageStatus.notYet,
      dartName: 'autofocus',
      reason:
          'A demo page is the payload of an iframe, and a field that takes focus on mount steals the caret from the page hosting it. Showing this honestly needs a mount-on-demand control the gallery does not have.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Focus ring',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'darkBorder',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Declared in Input.vue\'s props but never read by its template — a legacy toggle with no behaviour to port.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Validation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'helperText',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The web\'s own deprecated alias of `description`; a new API is not born with it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isClearable',
      status: CoverageStatus.shown,
      dartName: 'isClearable',
      shownBy: 'Affixes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isInvalid',
      status: CoverageStatus.shown,
      dartName: 'isInvalid',
      shownBy: 'Validation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placeholder',
      status: CoverageStatus.shown,
      dartName: 'placeholder',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'required',
      status: CoverageStatus.shown,
      dartName: 'required',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'revealPassword',
      status: CoverageStatus.shown,
      dartName: 'revealPassword',
      shownBy: 'Affixes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounded',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'type',
      status: CoverageStatus.shown,
      dartName: 'type',
      shownBy: 'Affixes',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'blur',
      status: CoverageStatus.shown,
      dartName: 'onBlur',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'clear',
      status: CoverageStatus.shown,
      dartName: 'onClear',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'focus',
      status: CoverageStatus.shown,
      dartName: 'onFocus',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'prefix',
      status: CoverageStatus.shown,
      dartName: 'prefix',
      shownBy: 'Affixes',
    ),
    CoverageEntry(
      section: 'slots',
      contractName: 'suffix',
      status: CoverageStatus.shown,
      dartName: 'suffix',
      shownBy: 'Affixes',
    ),
  ],
);

/// The contract coverage page for KunInput.
Widget kunInputContract(BuildContext context) =>
    const CoveragePage(coverage: _kunInput);

const ComponentCoverage _kunNull = ComponentCoverage(
  name: 'KunNull',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Default',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'isShowSticker',
      status: CoverageStatus.shown,
      dartName: 'isShowSticker',
      shownBy: 'Custom',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'src',
      status: CoverageStatus.shown,
      dartName: 'image',
      shownBy: 'Custom',
    ),
  ],
);

/// The contract coverage page for KunNull.
Widget kunNullContract(BuildContext context) =>
    const CoveragePage(coverage: _kunNull);

const ComponentCoverage _kunSwitch = ComponentCoverage(
  name: 'KunSwitch',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Help text',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Help text',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Events',
    ),
  ],
);

/// The contract coverage page for KunSwitch.
Widget kunSwitchContract(BuildContext context) =>
    const CoveragePage(coverage: _kunSwitch);

const ComponentCoverage _kunTextarea = ComponentCoverage(
  name: 'KunTextarea',
  entries: <CoverageEntry>[
    CoverageEntry(
      section: 'props',
      contractName: 'autoGrow',
      status: CoverageStatus.shown,
      dartName: 'autoGrow',
      shownBy: 'Growth',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'autofocus',
      status: CoverageStatus.notYet,
      dartName: 'autofocus',
      reason:
          'A demo page is the payload of an iframe, and a field that takes focus on mount steals the caret from the page hosting it. Showing this honestly needs a mount-on-demand control the gallery does not have.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'color',
      status: CoverageStatus.shown,
      dartName: 'color',
      shownBy: 'Focus ring',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'darkBorder',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Declared in Textarea.vue\'s props but never read by its template — a legacy toggle with no behaviour to port.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'description',
      status: CoverageStatus.shown,
      dartName: 'description',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'disabled',
      status: CoverageStatus.shown,
      dartName: 'disabled',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'error',
      status: CoverageStatus.shown,
      dartName: 'error',
      shownBy: 'Validation',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'hint',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The web\'s own deprecated alias of `description`; a new API is not born with it.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'label',
      status: CoverageStatus.shown,
      dartName: 'label',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'maxHeight',
      status: CoverageStatus.shown,
      dartName: 'maxHeight',
      shownBy: 'Growth',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'maxlength',
      status: CoverageStatus.shown,
      dartName: 'maxLength',
      shownBy: 'Count',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'minlength',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Feeds only the browser\'s submit-time constraint validation, which the component itself never renders; Flutter has no form submission for it to join.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'modelValue',
      status: CoverageStatus.shown,
      dartName: 'value',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'placeholder',
      status: CoverageStatus.shown,
      dartName: 'placeholder',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'readonly',
      status: CoverageStatus.shown,
      dartName: 'readOnly',
      shownBy: 'States',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'required',
      status: CoverageStatus.shown,
      dartName: 'required',
      shownBy: 'Labelling',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'resize',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'The drag handle is the browser\'s own textarea chrome (CSS `resize`); Flutter text fields have none, and drawing one would be design upstream never specified. The port renders the web default, `none`.',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rounded',
      status: CoverageStatus.shown,
      dartName: 'rounded',
      shownBy: 'Rounded',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'rows',
      status: CoverageStatus.shown,
      dartName: 'rows',
      shownBy: 'Growth',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'showCharCount',
      status: CoverageStatus.shown,
      dartName: 'showCharCount',
      shownBy: 'Count',
    ),
    CoverageEntry(
      section: 'props',
      contractName: 'size',
      status: CoverageStatus.shown,
      dartName: 'size',
      shownBy: 'Sizes',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'blur',
      status: CoverageStatus.shown,
      dartName: 'onBlur',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'focus',
      status: CoverageStatus.shown,
      dartName: 'onFocus',
      shownBy: 'Events',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'input',
      status: CoverageStatus.omitted,
      dartName: null,
      reason:
          'Carries the DOM event of each edit; the value it reports reaches onChanged (update:modelValue) on the same edit.',
    ),
    CoverageEntry(
      section: 'events',
      contractName: 'update:modelValue',
      status: CoverageStatus.shown,
      dartName: 'onChanged',
      shownBy: 'Events',
    ),
  ],
);

/// The contract coverage page for KunTextarea.
Widget kunTextareaContract(BuildContext context) =>
    const CoveragePage(coverage: _kunTextarea);
