// GENERATED by tool/gen_gallery.dart from gallery.spec.json and
// contracts/components.manifest.json — DO NOT EDIT.
// Regenerate: dart run tool/gen_gallery.dart

import 'coverage.g.dart';
import 'demos/alert.dart';
import 'demos/avatar.dart';
import 'demos/badge.dart';
import 'demos/button.dart';
import 'demos/card.dart';
import 'demos/chip.dart';
import 'demos/input.dart';
import 'demos/message.dart';
import 'demos/modal.dart';
import 'demos/null.dart';
import 'demos/select.dart';
import 'demos/skeleton.dart';
import 'demos/spinner.dart';
import 'demos/switch.dart';
import 'demos/tab.dart';
import 'demos/textarea.dart';
import 'demos/user_chip.dart';
import 'registry.dart';

/// Every component the gallery shows, in the order the index lists them.
const List<GalleryComponent> galleryComponents = <GalleryComponent>[
  GalleryComponent(
    slug: 'kunalert',
    name: 'KunAlert',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: alertBasic),
      GalleryDemo(slug: 'types', title: 'Types', builder: alertTypes),
      GalleryDemo(slug: 'options', title: 'Options', builder: alertOptions),
      GalleryDemo(slug: 'replace', title: 'Replaced', builder: alertReplace),
    ],
  ),
  GalleryComponent(
    slug: 'kunavatar',
    name: 'KunAvatar',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: avatarBasic),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: avatarSizes),
      GalleryDemo(
          slug: 'fallback', title: 'Sticker fallback', builder: avatarFallback),
      GalleryDemo(
          slug: 'navigation', title: 'Navigation', builder: avatarNavigation),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunAvatarContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunbadge',
    name: 'KunBadge',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: badgeBasic),
      GalleryDemo(slug: 'dot', title: 'Dot', builder: badgeDot),
      GalleryDemo(slug: 'max', title: 'Max', builder: badgeMax),
      GalleryDemo(slug: 'colors', title: 'Colors', builder: badgeColors),
      GalleryDemo(
          slug: 'standalone', title: 'Standalone', builder: badgeStandalone),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: badgeSizes),
      GalleryDemo(
          slug: 'placement', title: 'Placement', builder: badgePlacement),
      GalleryDemo(slug: 'count', title: 'Count', builder: badgeCount),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunBadgeContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunbutton',
    name: 'KunButton',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'matrix', title: 'Matrix', builder: buttonMatrix),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: buttonSizes),
      GalleryDemo(slug: 'states', title: 'States', builder: buttonStates),
      GalleryDemo(slug: 'rounded', title: 'Rounded', builder: buttonRounded),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunButtonContract),
    ],
  ),
  GalleryComponent(
    slug: 'kuncard',
    name: 'KunCard',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'anatomy', title: 'Anatomy', builder: cardAnatomy),
      GalleryDemo(slug: 'tints', title: 'Tints', builder: cardTints),
      GalleryDemo(slug: 'surfaces', title: 'Surfaces', builder: cardSurfaces),
      GalleryDemo(slug: 'padding', title: 'Padding', builder: cardPadding),
      GalleryDemo(slug: 'rounded', title: 'Rounded', builder: cardRounded),
      GalleryDemo(
          slug: 'interactive', title: 'Interactive', builder: cardInteractive),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunCardContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunchip',
    name: 'KunChip',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'matrix', title: 'Matrix', builder: chipMatrix),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: chipSizes),
      GalleryDemo(slug: 'parts', title: 'Parts', builder: chipParts),
      GalleryDemo(slug: 'dismiss', title: 'Dismiss', builder: chipDismiss),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunChipContract),
    ],
  ),
  GalleryComponent(
    slug: 'kuninput',
    name: 'KunInput',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: inputSizes),
      GalleryDemo(
          slug: 'labelling', title: 'Labelling', builder: inputLabelling),
      GalleryDemo(
          slug: 'validation', title: 'Validation', builder: inputValidation),
      GalleryDemo(slug: 'affixes', title: 'Affixes', builder: inputAffixes),
      GalleryDemo(
          slug: 'focus-ring', title: 'Focus ring', builder: inputFocusRing),
      GalleryDemo(slug: 'rounded', title: 'Rounded', builder: inputRounded),
      GalleryDemo(slug: 'events', title: 'Events', builder: inputEvents),
      GalleryDemo(slug: 'states', title: 'States', builder: inputStates),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunInputContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunmessage',
    name: 'KunMessage',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'types', title: 'Types', builder: messageTypes),
      GalleryDemo(
          slug: 'positions', title: 'Positions', builder: messagePositions),
      GalleryDemo(
          slug: 'persistent', title: 'Persistent', builder: messagePersistent),
      GalleryDemo(slug: 'dedup', title: 'Repeated', builder: messageDedup),
      GalleryDemo(slug: 'burst', title: 'Burst', builder: messageBurst),
      GalleryDemo(
          slug: 'over-modal', title: 'Over a modal', builder: messageOverModal),
    ],
  ),
  GalleryComponent(
    slug: 'kunmodal',
    name: 'KunModal',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: modalBasic),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: modalSizes),
      GalleryDemo(
          slug: 'placement', title: 'Placement', builder: modalPlacement),
      GalleryDemo(
          slug: 'scroll', title: 'Scroll behaviour', builder: modalScroll),
      GalleryDemo(
          slug: 'non-dismissable',
          title: 'Non-dismissable',
          builder: modalNonDismissable),
      GalleryDemo(slug: 'alert', title: 'Alert dialog', builder: modalAlert),
      GalleryDemo(slug: 'form', title: 'Form', builder: modalForm),
      GalleryDemo(slug: 'nested', title: 'Nested', builder: modalNested),
      GalleryDemo(slug: 'events', title: 'Events', builder: modalEvents),
      GalleryDemo(slug: 'bare', title: 'Without container', builder: modalBare),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunModalContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunnull',
    name: 'KunNull',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'default', title: 'Default', builder: nullDefault),
      GalleryDemo(slug: 'custom', title: 'Custom', builder: nullCustom),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunNullContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunselect',
    name: 'KunSelect',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: selectBasic),
      GalleryDemo(
          slug: 'clearable', title: 'Clearable', builder: selectClearable),
      GalleryDemo(slug: 'colors', title: 'Colors', builder: selectColors),
      GalleryDemo(
          slug: 'custom-option',
          title: 'Custom option',
          builder: selectCustomOption),
      GalleryDemo(slug: 'disabled', title: 'Disabled', builder: selectDisabled),
      GalleryDemo(slug: 'error', title: 'Error', builder: selectError),
      GalleryDemo(slug: 'multiple', title: 'Multiple', builder: selectMultiple),
      GalleryDemo(
          slug: 'searchable', title: 'Searchable', builder: selectSearchable),
      GalleryDemo(slug: 'async', title: 'Async', builder: selectAsync),
      GalleryDemo(
          slug: 'filter-bar', title: 'Filter bar', builder: selectFilterBar),
      GalleryDemo(
          slug: 'in-modal', title: 'In a modal', builder: selectInModal),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: selectSizes),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunSelectContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunskeleton',
    name: 'KunSkeleton',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: skeletonBasic),
      GalleryDemo(slug: 'shapes', title: 'Shapes', builder: skeletonShapes),
      GalleryDemo(slug: 'loaded', title: 'Loaded', builder: skeletonLoaded),
      GalleryDemo(
          slug: 'variants', title: 'Variants', builder: skeletonVariants),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunSkeletonContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunspinner',
    name: 'KunSpinner',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: spinnerSizes),
    ],
  ),
  GalleryComponent(
    slug: 'kunswitch',
    name: 'KunSwitch',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: switchSizes),
      GalleryDemo(slug: 'states', title: 'States', builder: switchStates),
      GalleryDemo(slug: 'help', title: 'Help text', builder: switchHelp),
      GalleryDemo(slug: 'events', title: 'Events', builder: switchEvents),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunSwitchContract),
    ],
  ),
  GalleryComponent(
    slug: 'kuntab',
    name: 'KunTab',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: tabBasic),
      GalleryDemo(slug: 'variants', title: 'Variants', builder: tabVariants),
      GalleryDemo(slug: 'colors', title: 'Colors', builder: tabColors),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: tabSizes),
      GalleryDemo(slug: 'vertical', title: 'Vertical', builder: tabVertical),
      GalleryDemo(slug: 'overflow', title: 'Overflow', builder: tabOverflow),
      GalleryDemo(slug: 'icons', title: 'Icons', builder: tabIcons),
      GalleryDemo(slug: 'align', title: 'Align', builder: tabAlign),
      GalleryDemo(slug: 'disabled', title: 'Disabled', builder: tabDisabled),
      GalleryDemo(slug: 'links', title: 'Links', builder: tabLinks),
      GalleryDemo(slug: 'custom', title: 'Custom tabs', builder: tabCustom),
      GalleryDemo(
          slug: 'scrollable', title: 'Scrollable', builder: tabScrollable),
      GalleryDemo(slug: 'contract', title: 'Contract', builder: kunTabContract),
    ],
  ),
  GalleryComponent(
    slug: 'kuntextarea',
    name: 'KunTextarea',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: textareaSizes),
      GalleryDemo(
          slug: 'labelling', title: 'Labelling', builder: textareaLabelling),
      GalleryDemo(
          slug: 'validation', title: 'Validation', builder: textareaValidation),
      GalleryDemo(slug: 'growth', title: 'Growth', builder: textareaGrowth),
      GalleryDemo(slug: 'count', title: 'Count', builder: textareaCount),
      GalleryDemo(
          slug: 'focus-ring', title: 'Focus ring', builder: textareaFocusRing),
      GalleryDemo(slug: 'rounded', title: 'Rounded', builder: textareaRounded),
      GalleryDemo(slug: 'events', title: 'Events', builder: textareaEvents),
      GalleryDemo(slug: 'states', title: 'States', builder: textareaStates),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunTextareaContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunuserchip',
    name: 'KunUserChip',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: userChipBasic),
      GalleryDemo(
          slug: 'description',
          title: 'Description',
          builder: userChipDescription),
      GalleryDemo(
          slug: 'truncate', title: 'Truncate', builder: userChipTruncate),
      GalleryDemo(
          slug: 'navigation', title: 'Navigation', builder: userChipNavigation),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunUserChipContract),
    ],
  ),
];

/// Components the manifest claims that the gallery has not reached.
const List<String> galleryUnbuiltComponents = <String>[];
