// GENERATED by tool/gen_gallery.dart from gallery.spec.json and
// contracts/components.manifest.json — DO NOT EDIT.
// Regenerate: dart run tool/gen_gallery.dart

import 'coverage.g.dart';
import 'demos/badge.dart';
import 'demos/button.dart';
import 'demos/card.dart';
import 'demos/chip.dart';
import 'demos/input.dart';
import 'demos/null.dart';
import 'demos/spinner.dart';
import 'demos/switch.dart';
import 'demos/textarea.dart';
import 'registry.dart';

/// Every component the gallery shows, in the order the index lists them.
const List<GalleryComponent> galleryComponents = <GalleryComponent>[
  GalleryComponent(
    slug: 'kunbadge',
    name: 'KunBadge',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'basic', title: 'Basic', builder: badgeBasic),
      GalleryDemo(slug: 'dot', title: 'Dot', builder: badgeDot),
      GalleryDemo(slug: 'max', title: 'Max', builder: badgeMax),
      GalleryDemo(slug: 'colors', title: 'Colors', builder: badgeColors),
      GalleryDemo(
          slug: 'standalone', title: 'Standalone', builder: badgeStandalone),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: badgeSizes),
      GalleryDemo(
          slug: 'placement', title: 'Placement', builder: badgePlacement),
      GalleryDemo(slug: 'count', title: 'Count', builder: badgeCount),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunBadgeContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunbutton',
    name: 'KunButton',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'matrix', title: 'Matrix', builder: buttonMatrix),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: buttonSizes),
      GalleryDemo(slug: 'states', title: 'States', builder: buttonStates),
      GalleryDemo(slug: 'rounded', title: 'Rounded', builder: buttonRounded),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunButtonContract),
    ],
  ),
  GalleryComponent(
    slug: 'kuncard',
    name: 'KunCard',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'anatomy', title: 'Anatomy', builder: cardAnatomy),
      GalleryDemo(slug: 'tints', title: 'Tints', builder: cardTints),
      GalleryDemo(slug: 'surfaces', title: 'Surfaces', builder: cardSurfaces),
      GalleryDemo(slug: 'padding', title: 'Padding', builder: cardPadding),
      GalleryDemo(slug: 'rounded', title: 'Rounded', builder: cardRounded),
      GalleryDemo(
          slug: 'interactive', title: 'Interactive', builder: cardInteractive),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunCardContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunchip',
    name: 'KunChip',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'matrix', title: 'Matrix', builder: chipMatrix),
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: chipSizes),
      GalleryDemo(slug: 'parts', title: 'Parts', builder: chipParts),
      GalleryDemo(slug: 'dismiss', title: 'Dismiss', builder: chipDismiss),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunChipContract),
    ],
  ),
  GalleryComponent(
    slug: 'kuninput',
    name: 'KunInput',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: inputSizes),
      GalleryDemo(
          slug: 'labelling', title: 'Labelling', builder: inputLabelling),
      GalleryDemo(
          slug: 'validation', title: 'Validation', builder: inputValidation),
      GalleryDemo(slug: 'affixes', title: 'Affixes', builder: inputAffixes),
      GalleryDemo(
          slug: 'focus-ring', title: 'Focus ring', builder: inputFocusRing),
      GalleryDemo(slug: 'rounded', title: 'Rounded', builder: inputRounded),
      GalleryDemo(slug: 'events', title: 'Events', builder: inputEvents),
      GalleryDemo(slug: 'states', title: 'States', builder: inputStates),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunInputContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunnull',
    name: 'KunNull',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'default', title: 'Default', builder: nullDefault),
      GalleryDemo(slug: 'custom', title: 'Custom', builder: nullCustom),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunNullContract),
    ],
  ),
  GalleryComponent(
    slug: 'kunspinner',
    name: 'KunSpinner',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: spinnerSizes),
    ],
  ),
  GalleryComponent(
    slug: 'kunswitch',
    name: 'KunSwitch',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: switchSizes),
      GalleryDemo(slug: 'states', title: 'States', builder: switchStates),
      GalleryDemo(slug: 'help', title: 'Help text', builder: switchHelp),
      GalleryDemo(slug: 'events', title: 'Events', builder: switchEvents),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunSwitchContract),
    ],
  ),
  GalleryComponent(
    slug: 'kuntextarea',
    name: 'KunTextarea',
    demos: <GalleryDemo>[
      GalleryDemo(slug: 'sizes', title: 'Sizes', builder: textareaSizes),
      GalleryDemo(
          slug: 'labelling', title: 'Labelling', builder: textareaLabelling),
      GalleryDemo(
          slug: 'validation', title: 'Validation', builder: textareaValidation),
      GalleryDemo(slug: 'growth', title: 'Growth', builder: textareaGrowth),
      GalleryDemo(slug: 'count', title: 'Count', builder: textareaCount),
      GalleryDemo(
          slug: 'focus-ring', title: 'Focus ring', builder: textareaFocusRing),
      GalleryDemo(slug: 'rounded', title: 'Rounded', builder: textareaRounded),
      GalleryDemo(slug: 'events', title: 'Events', builder: textareaEvents),
      GalleryDemo(slug: 'states', title: 'States', builder: textareaStates),
      GalleryDemo(
          slug: 'contract', title: 'Contract', builder: kunTextareaContract),
    ],
  ),
];

/// Components the manifest claims that the gallery has not reached.
const List<String> galleryUnbuiltComponents = <String>[];
