import 'dart:convert';
import 'dart:io';

const List<String> _sections = <String>['props', 'events', 'slots'];

const String _header = '''
// GENERATED by tool/gen_gallery.dart from gallery.spec.json and
// contracts/components.manifest.json — DO NOT EDIT.
// Regenerate: dart run tool/gen_gallery.dart
''';

Future<void> main(List<String> args) async {
  final File manifestFile = File('../../contracts/components.manifest.json');
  if (!manifestFile.existsSync()) {
    stderr.writeln('run this from apps/gallery');
    exit(2);
  }

  final String specPath = args.isEmpty ? 'gallery.spec.json' : args.first;
  final Map<String, dynamic> specJson = _readJson(File(specPath));
  final Map<String, dynamic> manifestJson = _readJson(manifestFile);

  final List<_SpecComponent> specComponents = _parseSpec(specJson);
  final Map<String, _ManifestComponent> manifest = _parseManifest(manifestJson);

  final List<String> errors = <String>[];
  for (final _SpecComponent component in specComponents) {
    final _ManifestComponent? claimed = manifest[component.name];
    if (component.hasContract && claimed == null) {
      errors.add('${component.name}: not in the manifest');
    }
    if (!component.hasContract) {
      for (final String name in component.undemoed.keys) {
        errors.add(
          '${component.name} $name: contract:false forbids shows and undemoed',
        );
      }
      for (final _SpecDemo demo in component.demos) {
        for (final String name in demo.shows) {
          errors.add(
            '${component.name} $name: contract:false forbids shows and undemoed',
          );
        }
      }
    }
    _checkDeclarations(component, claimed, errors);
  }

  if (errors.isNotEmpty) {
    for (final String error in errors) {
      stderr.writeln(error);
    }
    exit(1);
  }

  final Set<String> specNames = <String>{
    for (final _SpecComponent component in specComponents) component.name,
  };
  final List<String> unbuilt = <String>[
    for (final String name in manifest.keys)
      if (!specNames.contains(name)) name,
  ];
  for (final String name in unbuilt) {
    stdout.writeln(name);
  }

  final String coverageSource = _emitCoverage(specComponents, manifest);
  final String registrySource =
      _emitRegistry(specComponents, manifest, unbuilt);

  const String coveragePath = 'lib/src/coverage.g.dart';
  const String registryPath = 'lib/src/registry.g.dart';
  File(coveragePath).writeAsStringSync(coverageSource);
  File(registryPath).writeAsStringSync(registrySource);

  final ProcessResult format = await Process.run(
    Platform.resolvedExecutable,
    <String>['format', coveragePath, registryPath],
  );
  if (format.exitCode != 0) {
    stderr.write(format.stderr);
    exit(format.exitCode);
  }

  stdout.writeln(coveragePath);
  stdout.writeln(registryPath);
  int demoCount = 0;
  int coverageCount = 0;
  for (final _SpecComponent component in specComponents) {
    demoCount += component.demos.length;
    if (manifest.containsKey(component.name)) {
      demoCount += 1;
      coverageCount += 1;
    }
  }
  stdout.writeln(
    '${specComponents.length} components, $demoCount demos, '
    '$coverageCount coverage pages, ${unbuilt.length} unbuilt',
  );
}

Map<String, dynamic> _readJson(File file) {
  final Object? decoded = jsonDecode(file.readAsStringSync());
  final Map<String, dynamic>? map = _asMap(decoded);
  if (map == null) {
    stderr.writeln('${file.path}: expected a JSON object');
    exit(1);
  }
  return map;
}

List<_SpecComponent> _parseSpec(Map<String, dynamic> spec) {
  final Map<String, dynamic>? components = _asMap(spec['components']);
  if (components == null) {
    stderr.writeln('gallery.spec.json: missing components object');
    exit(1);
  }
  final List<_SpecComponent> parsed = <_SpecComponent>[];
  for (final MapEntry<String, dynamic> entry in components.entries) {
    final Map<String, dynamic>? body = _asMap(entry.value);
    if (body == null) {
      stderr.writeln('${entry.key}: expected a component object');
      exit(1);
    }
    final Object? source = body['source'];
    if (source is! String) {
      stderr.writeln('${entry.key}: missing source');
      exit(1);
    }
    final List<_SpecDemo> demos = <_SpecDemo>[];
    final Object? demosRaw = body['demos'];
    if (demosRaw is! List<dynamic>) {
      stderr.writeln('${entry.key}: missing demos list');
      exit(1);
    }
    for (final Object? demoRaw in demosRaw) {
      final Map<String, dynamic>? demo = _asMap(demoRaw);
      if (demo == null) {
        stderr.writeln('${entry.key}: demo is not an object');
        exit(1);
      }
      final Object? slug = demo['slug'];
      final Object? title = demo['title'];
      final Object? builder = demo['builder'];
      if (slug is! String || title is! String || builder is! String) {
        stderr.writeln('${entry.key}: demo is missing slug, title or builder');
        exit(1);
      }
      final List<String> shows = <String>[];
      final Object? showsRaw = demo['shows'];
      if (showsRaw != null) {
        if (showsRaw is! List<dynamic>) {
          stderr.writeln('${entry.key} $slug: shows is not a list');
          exit(1);
        }
        for (final Object? name in showsRaw) {
          if (name is! String) {
            stderr.writeln('${entry.key} $slug: shows entries must be strings');
            exit(1);
          }
          shows.add(name);
        }
      }
      demos.add(
        _SpecDemo(slug: slug, title: title, builder: builder, shows: shows),
      );
    }
    final Map<String, String> undemoed = <String, String>{};
    final Object? undemoedRaw = body['undemoed'];
    if (undemoedRaw != null) {
      final Map<String, dynamic>? undemoedMap = _asMap(undemoedRaw);
      if (undemoedMap == null) {
        stderr.writeln('${entry.key}: undemoed is not an object');
        exit(1);
      }
      for (final MapEntry<String, dynamic> undemoedEntry
          in undemoedMap.entries) {
        final Object? reason = undemoedEntry.value;
        if (reason is! String) {
          stderr.writeln(
            '${entry.key} ${undemoedEntry.key}: undemoed reason must be a string',
          );
          exit(1);
        }
        undemoed[undemoedEntry.key] = reason;
      }
    }
    parsed.add(
      _SpecComponent(
        name: entry.key,
        source: source,
        hasContract: body['contract'] != false,
        demos: demos,
        undemoed: undemoed,
      ),
    );
  }
  return parsed;
}

Map<String, _ManifestComponent> _parseManifest(Map<String, dynamic> json) {
  final Map<String, dynamic>? components = _asMap(json['components']);
  if (components == null) {
    stderr.writeln('components.manifest.json: missing components object');
    exit(1);
  }
  final Map<String, _ManifestComponent> parsed = <String, _ManifestComponent>{};
  for (final MapEntry<String, dynamic> entry in components.entries) {
    final Map<String, dynamic>? body = _asMap(entry.value);
    if (body == null) {
      stderr.writeln('${entry.key}: expected a manifest object');
      exit(1);
    }
    final List<_ManifestEntry> entries = <_ManifestEntry>[];
    final List<String> claimed = <String>[];
    for (final String section in _sections) {
      final Object? sectionRaw = body[section];
      if (sectionRaw == null) continue;
      final Map<String, dynamic>? sectionMap = _asMap(sectionRaw);
      if (sectionMap == null) {
        stderr.writeln('${entry.key}: $section is not an object');
        exit(1);
      }
      for (final MapEntry<String, dynamic> item in sectionMap.entries) {
        final Object? value = item.value;
        if (value is String) {
          entries.add(
            _ManifestEntry(
              section: section,
              contractName: item.key,
              dartName: value,
            ),
          );
          claimed.add('$section.${item.key}');
        } else {
          final Map<String, dynamic>? omitMap = _asMap(value);
          final Object? omit = omitMap?['omit'];
          if (omit is! String) {
            stderr.writeln(
              '${entry.key} $section.${item.key}: expected a dart name or omit',
            );
            exit(1);
          }
          entries.add(
            _ManifestEntry(
              section: section,
              contractName: item.key,
              reason: omit,
            ),
          );
        }
      }
    }
    parsed[entry.key] = _ManifestComponent(
      name: entry.key,
      entries: entries,
      claimed: claimed,
    );
  }
  return parsed;
}

void _checkDeclarations(
  _SpecComponent component,
  _ManifestComponent? claimed,
  List<String> errors,
) {
  final List<String> order = <String>[];
  final Map<String, int> counts = <String, int>{};
  void declare(String name) {
    if (!counts.containsKey(name)) {
      order.add(name);
    }
    counts[name] = (counts[name] ?? 0) + 1;
  }

  for (final _SpecDemo demo in component.demos) {
    for (final String name in demo.shows) {
      declare(name);
    }
  }
  for (final String name in component.undemoed.keys) {
    declare(name);
  }

  final List<String> claimedNames =
      claimed == null ? const <String>[] : claimed.claimed;
  final Set<String> claimedSet = claimedNames.toSet();
  for (final String name in claimedNames) {
    final int count = counts[name] ?? 0;
    if (count == 0) {
      errors.add('${component.name} $name: claimed but undeclared');
    }
  }
  for (final String name in order) {
    if (!claimedSet.contains(name)) {
      errors.add('${component.name} $name: declared but not claimed');
    }
  }
  for (final String name in order) {
    if ((counts[name] ?? 0) > 1) {
      errors.add('${component.name} $name: declared twice');
    }
  }
}

String _emitCoverage(
  List<_SpecComponent> specComponents,
  Map<String, _ManifestComponent> manifest,
) {
  final StringBuffer out = StringBuffer()
    ..writeln(_header)
    ..writeln("import 'package:flutter/widgets.dart';")
    ..writeln()
    ..writeln("import 'coverage.dart';")
    ..writeln();

  for (final _SpecComponent component in specComponents) {
    final _ManifestComponent? claimed = manifest[component.name];
    if (claimed == null) continue;
    final Map<String, String> shownBy = <String, String>{};
    for (final _SpecDemo demo in component.demos) {
      for (final String name in demo.shows) {
        shownBy[name] = demo.title;
      }
    }
    final String id = _lowerCamel(component.name);
    out
      ..writeln(
        'const ComponentCoverage _$id = ComponentCoverage(',
      )
      ..writeln('  name: ${_quote(component.name)},')
      ..writeln('  entries: <CoverageEntry>[');
    for (final _ManifestEntry entry in claimed.entries) {
      final String qualified = '${entry.section}.${entry.contractName}';
      out
        ..writeln('    CoverageEntry(')
        ..writeln('      section: ${_quote(entry.section)},')
        ..writeln('      contractName: ${_quote(entry.contractName)},')
        ..writeln('      dartName: ${_quoteOrNull(entry.dartName)},');
      final String? title = shownBy[qualified];
      if (title != null) {
        out.writeln('      shownBy: ${_quote(title)},');
      }
      final String? reason = title != null
          ? null
          : (entry.dartName == null
              ? entry.reason
              : component.undemoed[qualified]);
      if (reason != null) {
        out.writeln('      reason: ${_quote(reason)},');
      }
      out.writeln('    ),');
    }
    out
      ..writeln('  ],')
      ..writeln(');')
      ..writeln()
      ..writeln('/// The contract coverage page for ${component.name}.')
      ..writeln(
        'Widget ${id}Contract(BuildContext context) =>',
      )
      ..writeln('    const CoveragePage(coverage: _$id);')
      ..writeln();
  }
  return out.toString();
}

String _emitRegistry(
  List<_SpecComponent> specComponents,
  Map<String, _ManifestComponent> manifest,
  List<String> unbuilt,
) {
  final List<String> imports = <String>{
    'coverage.g.dart',
    'registry.dart',
    for (final _SpecComponent component in specComponents) component.source,
  }.toList()
    ..sort();

  final StringBuffer out = StringBuffer()..writeln(_header);
  for (final String import in imports) {
    out.writeln("import '${import.replaceAll("'", r"\'")}';");
  }
  out
    ..writeln()
    ..writeln(
      '/// Every component the gallery shows, in the order the index lists them.',
    )
    ..writeln(
      'const List<GalleryComponent> galleryComponents = <GalleryComponent>[',
    );

  for (final _SpecComponent component in specComponents) {
    out
      ..writeln('  GalleryComponent(')
      ..writeln('    slug: ${_quote(component.name.toLowerCase())},')
      ..writeln('    name: ${_quote(component.name)},')
      ..writeln('    demos: <GalleryDemo>[');
    for (final _SpecDemo demo in component.demos) {
      out.writeln(
        '      GalleryDemo(slug: ${_quote(demo.slug)}, title: ${_quote(demo.title)}, builder: ${demo.builder}),',
      );
    }
    if (manifest.containsKey(component.name)) {
      final String builder = '${_lowerCamel(component.name)}Contract';
      out.writeln(
        "      GalleryDemo(slug: 'contract', title: 'Contract', builder: $builder),",
      );
    }
    out
      ..writeln('    ],')
      ..writeln('  ),');
  }
  out
    ..writeln('];')
    ..writeln()
    ..writeln(
      '/// Components the manifest claims that the gallery has not reached.',
    )
    ..writeln(
      'const List<String> galleryUnbuiltComponents = <String>[',
    );
  for (final String name in unbuilt) {
    out.writeln('  ${_quote(name)},');
  }
  out.writeln('];');
  out.writeln();
  return out.toString();
}

Map<String, dynamic>? _asMap(Object? value) {
  if (value is Map<String, dynamic>) return value;
  if (value is Map) {
    return <String, dynamic>{
      for (final MapEntry<dynamic, dynamic> entry in value.entries)
        entry.key as String: entry.value,
    };
  }
  return null;
}

String _lowerCamel(String name) {
  if (name.isEmpty) return name;
  return '${name[0].toLowerCase()}${name.substring(1)}';
}

String _quote(String value) {
  final String escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\t', r'\t');
  return "'$escaped'";
}

String _quoteOrNull(String? value) => value == null ? 'null' : _quote(value);

class _SpecComponent {
  _SpecComponent({
    required this.name,
    required this.source,
    required this.hasContract,
    required this.demos,
    required this.undemoed,
  });

  final String name;
  final String source;
  final bool hasContract;
  final List<_SpecDemo> demos;
  final Map<String, String> undemoed;
}

class _SpecDemo {
  _SpecDemo({
    required this.slug,
    required this.title,
    required this.builder,
    required this.shows,
  });

  final String slug;
  final String title;
  final String builder;
  final List<String> shows;
}

class _ManifestComponent {
  _ManifestComponent({
    required this.name,
    required this.entries,
    required this.claimed,
  });

  final String name;
  final List<_ManifestEntry> entries;
  final List<String> claimed;
}

class _ManifestEntry {
  _ManifestEntry({
    required this.section,
    required this.contractName,
    this.dartName,
    this.reason,
  });

  final String section;
  final String contractName;
  final String? dartName;
  final String? reason;
}
