name: kun_ui_gallery
publish_to: none

environment:
  sdk: ^3.6.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  kun_ui: ^0.7.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
